/**
 * SUTRADHAR'S FILE — the orchestrator. Wires PRAHARI's detection module and
 * VAANI's AI module together, per backend/api/CONTRACT.md. PRAHARI and VAANI:
 * do not edit this file — replace the logic inside your own module and this
 * will pick it up automatically, since it only calls your exported function.
 */

const { detectScamPatterns } = require("../detection/scamDetector");
const { generateExplanation } = require("../ai/explainRisk");

// In-memory case store for local/Build It mode. DRISHYA/infra can swap this
// for DynamoDB in Ship It mode without changing the function signature below.
const localCaseStore = new Map();

function generateCaseId() {
  return "case_" + Date.now().toString(36) + "_" + Math.random().toString(36).slice(2, 8);
}

/**
 * @param {{ language: "hi"|"en", inputType: "text"|"image", rawText?: string, imageBase64?: string }} request
 * @returns {Promise<object>} response body matching CONTRACT.md
 */
async function analyze(request) {
  const { language, inputType, rawText } = request;

  if (inputType === "image") {
    // OCR is optional/stretch per CONTRACT.md — until wired up, require rawText.
    if (!rawText) {
      throw new Error(
        "Image OCR not yet wired up. Provide rawText as a fallback until OCR is added."
      );
    }
  }

  const text = rawText || "";

  const { riskLevel, matchedPatterns } = detectScamPatterns(text);
  const { explanation, checklist } = await generateExplanation({
    riskLevel,
    matchedPatterns,
    language,
  });

  const caseId = generateCaseId();
  const responseBody = {
    caseId,
    riskLevel,
    matchedPatterns,
    explanation,
    checklist,
    reportingLinks: {
      helpline: "1930",
      portal: "https://cybercrime.gov.in/",
    },
  };

  localCaseStore.set(caseId, { request, responseBody, createdAt: new Date().toISOString() });

  return responseBody;
}

// Lambda entry point (API Gateway proxy integration shape)
exports.handler = async (event) => {
  try {
    const body = typeof event.body === "string" ? JSON.parse(event.body) : event.body;
    const result = await analyze(body);
    return {
      statusCode: 200,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(result),
    };
  } catch (err) {
    return {
      statusCode: 400,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ error: err.message }),
    };
  }
};

exports.analyze = analyze;

// Quick manual smoke test: `node backend/api/analyzeHandler.js`
if (require.main === module) {
  analyze({
    language: "en",
    inputType: "text",
    rawText: "URGENT: Your account will be blocked. Share your OTP immediately to verify.",
  }).then((result) => {
    console.log("Smoke test result:\n", JSON.stringify(result, null, 2));
  });
}
